# Use the official MySQL base image
FROM mysql:9.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=exampledb
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=userpassword

# Copy the initialization script
COPY init.sql /docker-entrypoint-initdb.d/

# Expose MySQL port
EXPOSE 3306

CMD [ "mysqld" ]